version: "3.8"

services:
  postgres-shared:
    container_name: postgres-kc
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: kc_db # Nom de la base de données
      POSTGRES_USER: ${USER_BD} # Utilisateur principal
      POSTGRES_PASSWORD: ${PSW_DB} # Mot de passe
    ports:
      - "5499:5432" # Port pour accéder à PostgreSQL depuis l'hôte
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw # Données persistantes
      - ./postgres_home/backups:/var/backups:rw # Dossier de sauvegarde
      - ./postgres_home/init:/docker-entrypoint-initdb.d:rw # Scripts d'initialisation
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_BD} -d kc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - company-network
volumes:
  postgres_data:
    name: PG_DATA

networks:
  company-network:
    external: true
    name: company_network
