services:
  redis-shared:
    image: redis:7-alpine

    secrets:
      - redis_password

    # IMPORTANT: on force un shell, sinon "export" / "$(cat ...)" ne s'exécute pas
    command: >
      sh -c 'REDIS_PASSWORD="$$(cat /run/secrets/redis_password)";
             exec redis-server
               --requirepass "$$REDIS_PASSWORD"
               --appendonly yes
               --maxmemory 1gb
               --maxmemory-policy allkeys-lru'

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis_data:/data

    deploy:
      replicas: 1

      resources:
        limits:
          memory: 1200mb        # Limite Docker (un peu plus que Redis)
        reservations:
          memory: 256mb        # Mémoire réservée minimum

      placement:
        constraints: [node.hostname == BlackHole]

      restart_policy:
        condition: any
        max_attempts: 3

    networks:
      - company-network
    healthcheck:
      # On lit le secret au moment du test (pas de variable .env)
      test:
        [
          "CMD-SHELL",
          'redis-cli -a "$$(cat /run/secrets/redis_password)" ping | grep -q PONG'
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    name: REDIS_DATA

networks:
  company-network:
    external: true
    name: company_network

secrets:
  redis_password:
    external: true