version: "3.8"

services:
  redis:
    image: redis:7-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD} 
      --appendonly yes
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 1200mb        # Limite Docker (un peu plus que Redis)
        reservations:
          memory: 256mb        # Mémoire réservée minimum
      replicas: 1
      placement:
        constraints: [node.hostname == BlackHole]
      restart_policy:
        condition: any
        max_attempts: 3
    networks:
      - company-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    name: REDIS_DATA

networks:
  company-network:
    external: true
    name: company_network