version: "3.8"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_HOSTNAME: "${KEYCLOAK_FRONTEND_URL}"
      KC_HOSTNAME_STRICT: "false"
      KC_COOKIE_SAME_SITE: None
      KC_COOKIE_SECURE: "false"
      KC_LOG_CONSOLE_LEVEL: info
      KC_LOG_CONSOLE_COLOR: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-shared:5432/${DB_NAME}
      KC_DB_USERNAME: ${USER_BD}
      KC_DB_PASSWORD: ${PSW_DB}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      JAVA_OPTS_APPEND: "-Dkeycloak.someOption=value -XX:MaxRAMPercentage=65"
    volumes:
      - ../../script/wait-for-it.sh:/wait-for-it.sh
      - keycloak_data:/opt/keycloak/data # Données persistantes
    entrypoint: [
      "./wait-for-it.sh",
      "postgres-shared:5432", # DNS interne docker => hostname:port
      "--",
      "/opt/keycloak/bin/kc.sh",
      "start-dev",
    ]
    ports:
      - "${KEYCLOAK_PORT}:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
    networks:
      - company-network

volumes:
  keycloak_data:
    name: KEYCLOAK_DATA

networks:
  company-network:
    external: true
    name: company_network
